name: test_repo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_staggered_grid_view: ^0.7.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  google_fonts: ^6.2.1
  http: ^1.2.1
  meta: ^1.11.0
  riverpod_annotation: ^2.3.5
  riverpod_generator: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/home.svg
    - lib/assets/search.svg
    - lib/assets/create.svg
    - lib/assets/inbox.svg
